- name: Creating ec2 instances and adding to the rute53 records
  hosts: localhost
  connection: local
  tasks:
   - name: Launch an EC2 Instance
     amazon.aws.ec2_instance:
      name: "mysql"
      image_id: "ami-09c813fb71547fc4f" # Replace with your desired AMI ID
      instance_type: "t3.micro"
      security_group: "sg-0d7d38fd2dd9739a0" # Or security_group_ids: ["sg-0123456789abcdef0"]
     register: instance_output


