- name: Setup mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql 
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: setting up the root user 
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

  - name: enabling and starting the mysql
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes